src: include node_internals.h in node_metadata.cc
Currently, if configured --without-ssl the following compiler error will
be generated:
../src/node_metadata.cc:29:12:
error: use of undeclared identifier 'llhttp_version'
  llhttp = llhttp_version;
           ^
../src/node_metadata.cc:30:17:
error: use of undeclared identifier 'http_parser_version'
  http_parser = http_parser_version;

This commit includes the node_internals.h header so that
llhttp_version and http_parser_versions are always available.

PR-URL: https://github.com/nodejs/node/pull/24933
Reviewed-By: Ben Noordhuis <info@bnoordhuis.nl>
Reviewed-By: Richard Lau <riclau@uk.ibm.com>
Reviewed-By: Joyee Cheung <joyeec9h3@gmail.com>
Reviewed-By: Colin Ihrig <cjihrig@gmail.com>
Reviewed-By: Anna Henningsen <anna@addaleax.net>